### ISSUE TITLE
Nova stuck on displaying errors already fixed by Nova ESLint plugin

### ISSUE THREAD

**Issue by destegabry** [apexskier/nova-eslint#2] opened 2020-10-30 08:47 UTC
I have enabled the "fix on save" option, I get the obvious errors fixed by the Nova ESlint plugin but the errors remain visible in the editor.

Maybe it could be fixed enabling some sort of debounced-validate-as-you-type behavior.

**To reproduce**

1. extend `eslint:recommended` in your `.eslintrc` file
2. remove a semicolon from the code
3. save the file, note that the missing semicolon will be automatically added 
4. See the "insert ;" error even if the semicolon is now present

**Expected behavior**

The error doesn't appear.

**Screenshots**

<img width="297" alt="Schermata 2020-10-29 alle 09 44 46" src="https://user-images.githubusercontent.com/4654358/97545634-955eb700-19cb-11eb-8e68-ef4f68b85b31.png">

**Environment**

- Nova version: 2 (213794)
- Extension version: 1.3.0]
- ESLint version: 7.12.0
- macOS version: 10.15.7
- NodeJS information:
  - node version: 14.13.1
  - npm version: 6.14.8
  - installation method: homebrew

**Extension console output**

```
ESLint[9:43:52.827000] Fixing [path/to/my/]customHook.tsx
```

**Comment by destegabry** [comment] 2020-11-02 09:05
Just tested v1.5.0, it behaves much better. 

Seems it needs a lot of time before having the errors shown on the editor (5-6 seconds), while manually fixed errors disappears immediately.

Sorry, I'm a bit nitpicking 😅

**Comment by apexskier** [comment] 2020-11-02 18:03
Yeah, I'm generally aware of the slowness to initially show issues. The extension runs ESLint in an external process and it needs to verify that you've installed the proper plugins first, which is slower than I'd like. The former part is necessary to use the ESLint installed in your workspace, which is an intentional feature. The latter (plugin checking) is something I might be able to optimize in the future but currently works as intended.

When auto-fixing, I'm able to use the metadata for each issue to fix without directly saving and programmatically clear the issue. When you manually fix an errors Nova itself automatically hides the issue relevant to the modified range of text. This is why fixes go away fast.

I'm going to close this issue for now, since the main issue has been resolved. Thanks for helping out!

**Closed as completed by apexskier** 2020-11-02 18:03 UTC
Labels: bug

**Comment by destegabry** [comment] 2020-11-03 08:24
Thank you for the explanation and the great work you're putting in this plugin!
