### ISSUE TITLE
auto fix not working

### ISSUE THREAD

**Issue by saltnpixels** [apexskier/nova-eslint#281] opened 2022-03-23 23:56 UTC
I wrote 

```js
let e = 'the';
```

I asked eslint to fix all issues and expected it to turn it into a const. That did not happen. 
Does that mean eslint is not working for me?
In vscode it transforms it...

I'm using the latest nova build. I'm testing it out in the trial.

**Comment by apexskier** [comment] 2022-03-31 00:03
Probable duplicate of #277

**Closed as completed** 2022-03-31 00:03 UTC
Labels: bug, duplicate
